### ISSUE TITLE
computer-graphics_list of experiments_clipping : line_quiz"

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-graphics-iiith#103]
**Defect description:** radio buttons are not defined**steps to reproduce the issue:**direct link: http://cse18-iiith.vlabs.ac.in/exp7/quizzes.html?domain=computer%20science&lab=computer%20graphics**expected result:** radio buttons to write the quiz and evaluate**actual result:** no radio buttons**environment:**os: windows 10**browsers:** firefox-60.0.1 ,chrome-67.0.3396.62**attachments:**![cg-radio-buttons](https://gitlab.com/manikanta.annavarapu/virtual-labs-internship-amanikanta/uploads/221a1108f7b2e903bd4f7b2afca1583b/cg-radio-buttons.png)

**Comment by kurasaiteja** [comment]
same issue #91
