### ISSUE TITLE
QA_Clipping: Line_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#11]
Defect Description :
In "Clipping: Line" experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user  

Actual Result :
In "Clipping: Line" experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Clipping%20Line/Clipping%20Line_26_Back%20to%20experiments_smk.org

Attachment:
![cg24](https://cloud.githubusercontent.com/assets/14869397/14735869/2591a338-0891-11e6-9160-c044ef844da6.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
