### ISSUE TITLE
QA_Projections and Cameras_Quiz_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#16]
Defect Description :
When we click on the Quiz link of "Projections and Cameras" experiment  it is redirecting to blank page instead it should redirect to the quiz page  

Actual Result :
When we click on the Quiz link of "Projections and Cameras " experiment it is redirecting to blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Projections%20and%20Cameras/Projections%20and%20Cameras_09_Quiz_smk.org

Attachment:
![cg19](https://cloud.githubusercontent.com/assets/14869397/14735480/b5bc45ba-088e-11e6-9af5-551970d41a8b.png)

**Comment by khushpreet-kaur** [comment]
@BSravanthi , Source code doesn't contain questions for this experiment. This needs to be discussed with Lalit and integration team before taking any action.

**Comment by sravanthimodepu** [comment]
@khushpreet-kaur , Instead of blank page, update the Quiz page as "This section will  be updated soon"  or "Under Construction".

**Comment by khushpreet-kaur** [comment]
Done.

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
