### ISSUE TITLE
QA_Hierarchical Transformations: 3D Articulated Arm_Quiz_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#19]
Defect Description :
When we click on the Quiz link of "Hierarchical Transformations: 3D Articulated Arm" experiment  it is redirecting to blank page where it should redirect to the Quiz page. 

Actual Result :
When we click on the Quiz link of "Hierarchical Transformations: 3D Articulated Arm" experiment  it is redirecting to blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Hierarchical%20Transformations%203D/Hierarchical%20Transformations%203D_09_Quiz_smk.org

Attachment:
![cg16](https://cloud.githubusercontent.com/assets/14869397/14735334/03e76090-088e-11e6-9bee-21a927f808bd.png)

**Comment by khushpreet-kaur** [comment]
@BSravanthi , Source code doesn't contain questions for this experiment. This needs to be discussed with Lalit and integration team before taking any action.

**Comment by sravanthimodepu** [comment]
@khushpreet-kaur , Instead of blank page, update the Quiz page as "This section will  be updated soon"  or "Under Construction".

**Comment by khushpreet-kaur** [comment]
Done.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
