### ISSUE TITLE
QA_Rasterization: Polygon_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#2]
Defect Description :
In "Rasterization: Polygon" experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user 

Actual Result :
In "Rasterization: Polygon" experiment, the back to experiments link is not present in the page 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Rasterization%20Polygon/Rasterization%20Polygon_19_Back%20to%20experiments_smk.org

Attachment:
![cg33](https://cloud.githubusercontent.com/assets/14869397/14735984/d28c9ae8-0891-11e6-9875-b232f2b0353b.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
