### ISSUE TITLE
QA_Hierarchical Transformations: 2D Demo_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#20]
Defect Description :
In "Hierarchical Transformations: 2D Demo" experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user  

Actual Result :
In "Hierarchical Transformations: 2D Demo" experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Hierarchical%20Transformations%202D/Hierarchical%20Transformations%202D_20_Back%20to%20experiments_smk.org

Attachment:
![cg15](https://cloud.githubusercontent.com/assets/14869397/14735322/ef17ae86-088d-11e6-99f5-f99f1c53cd01.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
