### ISSUE TITLE
QA_Hierarchical Transformations: 2D Demo_Feedback_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#21]
Defect Description :
In Feedback page of "Hierarchical Transformations: 2D Demo" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) instead it should redirect to the feedback page  

Actual Result :
In the "Cepheid Variables" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Hierarchical%20Transformations%202D/Hierarchical%20Transformations%202D_19_Feedback_p2.org

Attachment:
![cg14](https://cloud.githubusercontent.com/assets/14869397/14735314/e16d4e80-088d-11e6-9057-90c5a46e0774.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine. User is able to give feedback now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
