### ISSUE TITLE
QA_Transformations: Translation_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#29]
Defect Description :
In "Transformations: Translation" experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user 

Actual Result :
In "Transformations: Translation" experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Transformations%20Translation/Transformations%20Translation_20_Back%20to%20experiments_smk.org

Attachment:
![cg6](https://cloud.githubusercontent.com/assets/14869397/14735080/787390a2-088c-11e6-8b8a-b814b77e93ab.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
