### ISSUE TITLE
QA_Rasterization: Polygon_Feedback_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#3]
Defect Description :
In Feedback page of "Rasterization: Polygon" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) instead it should redirect to a feedback page

Actual Result :
In the Feedback of "Rasterization: Polygon" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Rasterization%20Polygon/Rasterization%20Polygon_18_Feedback_p2.org

Attachment:
![cg32](https://cloud.githubusercontent.com/assets/14869397/14735960/b02d4ce0-0891-11e6-881e-0bf378d9f8af.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now. Link is working fine.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
