### ISSUE TITLE
QA_Points and Co-ordinate Systems_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#32]
Defect Description :
In "Points and Co-ordinate Systems" experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user

Actual Result :
In "Points and Co-ordinate Systems" experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Points%20and%20Co-ordinate%20Systems/Points%20and%20Co-ordinate%20Systems_20_Back%20to%20experiments_smk.org

Attachment:
![cg3](https://cloud.githubusercontent.com/assets/14869397/14735021/15a11da0-088c-11e6-918c-c3d7055c82de.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
