### ISSUE TITLE
QA_Points and Co-ordinate Systems_Feedback_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#33]
Defect Description :
In Feedback page of "Points and Co-ordinate Systems" experiment,  when we click on the  feedback link displayed on the screen , it is redirecting to an error page (404) instead it should redirect to the feedback page .

Actual Result :
In the "Cepheid Variables" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Points%20and%20Co-ordinate%20Systems/Points%20and%20Co-ordinate%20Systems_19_Feedback_p2.org

Attachment:
![cg2](https://cloud.githubusercontent.com/assets/14869397/14735009/fb35c358-088b-11e6-8e37-e408db18cb24.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine.

**Comment by khushpreet-kaur** [comment]
Link is working fine.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
