### ISSUE TITLE
QA_Points and Co-ordinate Systems_Quiz_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#34]
Defect Description :
In the Quiz page of "Points and Co-ordinate Systems" experiment  the cancel button is not present  where cancel button should be there.

Actual Result :
In the Quiz page of "Points and Co-ordinate Systems" experiment  the cancel button is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Points%20and%20Co-ordinate%20Systems/Points%20and%20Co-ordinate%20Systems_12_Quiz_p1.org

Attachment:
![cg1](https://cloud.githubusercontent.com/assets/14869397/14734983/c753c40e-088b-11e6-9acc-625feea68dc8.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now. Issue is resolved. User is able to give feedback now.

**Comment by khushpreet-kaur** [comment]
Button has been added to cancel/unset the selected options.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
