### ISSUE TITLE
QA_Computer_Graphics_Quiz_Images

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/computer-graphics-iiith#42]
Defect Description :
While testing this lab, found an issue in the quiz section. Images for the quiz qustions in the quiz section are not uploaded. Whereas the images for the quiz questions should be uploaded. Unable to copy the images in the quiz section.

Actual Result :
While testing this lab, found an issue in the quiz section. The images for the quiz questions should be uploaded.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by BSravanthi** [comment]
Fixed
