### ISSUE TITLE
QA_Computer-Graphics_Courses-Aligned_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#45]
Defect Description :
In the Courses aligned page of the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Courses aligned page of the Computer Graphics lab, found spelling mistakes. Refer to attachments.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i01](https://cloud.githubusercontent.com/assets/13479177/26099072/4b07c97e-3a47-11e7-8f0b-4f8857c276e1.png)

**Comment by BSravanthi** [comment]
Corrected the spelling mistakes.

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed
