### ISSUE TITLE
QA_Computer-graphics_Points & Co-ordinate-Systems_Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#46]
In the Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page. 

Attachments; 
![qa_oe_cg_i02](https://cloud.githubusercontent.com/assets/13479177/26099484/7eafbf06-3a48-11e7-8a00-c56d7be2bad7.png)

**Comment by sravanthimodepu** [comment]
Closing.
