### ISSUE TITLE
QA_Computer-graphics_Transformations: Translation Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#50]
In the Transformations: Translation lab's Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page.

Attachments:
![qa_oe_cg_i06](https://cloud.githubusercontent.com/assets/13479177/26101024/620407fe-3a4d-11e7-9ce3-8639b1e585c5.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing.
