### ISSUE TITLE
QA_Computer-graphics_Transformations: Rotation_Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#54]
In the Transformations: Rotation experiment's Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page.

Attachments:
![qa_oe_cg_i10](https://cloud.githubusercontent.com/assets/13479177/26103049/6600621e-3a55-11e7-801e-bee124f26428.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing.
