### ISSUE TITLE
QA_Computer-graphics_Transformations: Scaling_Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#56]
In the Transformations: Scaling experiment's Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page.

Attachments:
![qa_oe_cg_i12](https://cloud.githubusercontent.com/assets/13479177/26103490/60679b36-3a57-11e7-993f-2dad6b9089f8.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing
