### ISSUE TITLE
QA_Rasterization: Line_Feedback_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#6]
Defect Description :
In Feedback page of "Rasterization: Line" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) instead it should redirect to a feedback page

Actual Result :
In Feedback page of "Rasterization: Line" experiment,  when we click on the feedback link displayed on the screen , it is redirecting to an error page (404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Rasterization%20Line/Rasterization%20Line_18_Feedback_p2.org

Attachment:
![cg29](https://cloud.githubusercontent.com/assets/14869397/14735929/87e9b9c6-0891-11e6-9722-862032735167.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the Issue.
