### ISSUE TITLE
QA_Computer-graphics_Hierarchical Transformations: 2D Demo_Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#61]
In the Hierarchical Transformations: 2D Demo experiment's Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page.

Attachments:
![qa_oe_cg_i17](https://cloud.githubusercontent.com/assets/13479177/26104320/f0fd9418-3a5a-11e7-9049-bfdd6f27295a.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
closing.
