### ISSUE TITLE
QA_Computer-graphics_Hierarchical Transformations:3D Articulated Arm_Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#65]
In the Hierarchical Transformations:3D Articulated Arm experiment's Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page.

Attachments:
![qa_oe_cg_i22](https://cloud.githubusercontent.com/assets/13479177/26140865/ae952612-3af6-11e7-9165-83423aaf76a8.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
