### ISSUE TITLE
QA_Computer-Graphics_Hierarchical Transformations: 3D Articulated Arm_Procedure_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#66]
Defect Description :
In the Procedure page of Hierarchical Transformations: 3D Articulated Arm experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Procedure page of Hierarchical Transformations: 3D Articulated Arm experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i23](https://cloud.githubusercontent.com/assets/13479177/26142030/66bd6a10-3afc-11e7-84c5-9611ad71a83f.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
