### ISSUE TITLE
QA_Computer-Graphics_Projections-and-Cameras_Theory_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#69]
Defect Description :
In the Theory page of Projections and Cameras experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Theory page of Projections and Cameras experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i26](https://cloud.githubusercontent.com/assets/13479177/26143082/098e5818-3b01-11e7-9ef6-29becc8b4cb6.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing.
