### ISSUE TITLE
QA_Rasterization: Line_Quiz_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/computer-graphics-iiith#7]
Defect Description :
In the Quiz page of "Rasterization: Line" experiment  it is redirecting to Quiz page  but nothing is displayed in the page where the questions should be present in the page 

Actual Result :
In the Quiz page of "Rasterization: Line" experiment  it is redirecting to Quiz page  but nothing is displayed in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-graphics-iiith/blob/master/test-cases/integration_test-cases/Rasterization%20Line/Rasterization%20Line_08_Quiz_smk.org

Attachment:
![cg28](https://cloud.githubusercontent.com/assets/14869397/14735901/5e814504-0891-11e6-928f-c74f7a14e95a.png)

**Comment by khushpreet-kaur** [comment]
@BSravanthi , Source code doesn't contain questions for this experiment. This needs to be discussed with Lalit and integration team before taking any action.

**Comment by sravanthimodepu** [comment]
@khushpreet-kaur , Instead of blank page , update the Quiz page as "This section will be updated soon" or "Under Construction".

**Comment by khushpreet-kaur** [comment]
Done.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
