### ISSUE TITLE
QA_Computer-graphics_Projections-and-Cameras_Manual

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#70]
In the Projections and Cameras experiment's Manual provided simply a link to download the manual. We have added some text to improve the look and feel of the page.

Attachments:
![qa_oe_cg_i27](https://cloud.githubusercontent.com/assets/13479177/26143327/1ccf2a28-3b02-11e7-8578-c846e0090e38.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing.
