### ISSUE TITLE
QA_Computer-Graphics_Projections-and-Cameras_Procedure_Spelling-mistakes 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#71]
Defect Description :
In the Procedure page of Projections and Cameras experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Procedure page of Projections and Cameras experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i28](https://cloud.githubusercontent.com/assets/13479177/26145284/89621194-3b09-11e7-8a21-1355e6c5ef7b.png)

**Comment by BSravanthi** [comment]
Fixed.

**Comment by sravanthimodepu** [comment]
Closing.
