### ISSUE TITLE
QA_Order-of-the-menu_Clipping : Line

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#75]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cg_i33](https://cloud.githubusercontent.com/assets/13479177/26146132/af98a5f0-3b0c-11e7-9134-b3119fbd4e77.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing.
