### ISSUE TITLE
QA_Clipping : Polygon_Quizzes_User

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#77]
Defect Description :
In the Quizzes page of the Clipping : Polygon experiment, the "Show Answer" button is disabled when we log in as user. Where as when we log in as admin we can find this button in the quizzes section. Need to clear the discrepancy in order to maintain the quality of the service.

Actual Result :
In the Quizzes page of the Clipping : Polygon experiment, the "Show Answer" button is disabled when we log in as user. Where as when we log in as admin we can find this button in the quizzes section.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
**When Logged in as User**

![qa_oe_cg_i36](https://cloud.githubusercontent.com/assets/13479177/26146593/5689e300-3b0e-11e7-95f5-4c1ff81761a5.png)

**When Logged in as Admin**

![qa_oe_cg_i37](https://cloud.githubusercontent.com/assets/13479177/26146621/79957166-3b0e-11e7-9692-7add9b5ece7e.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
