### ISSUE TITLE
QA_Computer-Graphics_Rasterization : Line_Introduction_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#80]
Defect Description :
In the Introduction page of Rasterization : Line experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Introduction page of Rasterization : Line experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i39](https://cloud.githubusercontent.com/assets/13479177/26149642/a20d0d02-3b18-11e7-8b5e-2b8f48a48e0d.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
