### ISSUE TITLE
QA_Computer-Graphics_Rasterization : Line_Theory_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#81]
Defect Description :
In the Theory page of Rasterization : Line experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Theory page of Rasterization : Line experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i40](https://cloud.githubusercontent.com/assets/13479177/26149889/b75d09b8-3b19-11e7-900b-9e0354e6e555.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
